# Generated by Django 5.0.6 on 2024-06-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_imagemproduto_produto_imagens'),
    ]

    operations = [
    ]
