# Generated by Django 5.0.6 on 2024-06-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20240625_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(default='Cliente Padrão', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_cartao',
            field=models.CharField(default='0000000000000000', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(default='00000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemproduto',
            name='imagem',
            field=models.ImageField(upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
