# Generated by Django 5.0.6 on 2024-06-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='exibir_na_home',
            field=models.BooleanField(default=True),
        ),
    ]
